#!/bin/bash

#----------------------------------------------------------------------------
# MIT License
# 
# Copyright (c) 2018 Gabriel Capella
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#----------------------------------------------------------------------------
#
# This source code is part of my final undergraduate thesis.
# For any suggestion, doubt or comment send an email to
# gabriel@capella.pro
#
#----------------------------------------------------------------------------

set -e # exit

source ../bin/helper.sh
load_c_defines

echo "memory_initialization_radix=16;" > pmem.coe
echo "memory_initialization_vector=10;" >> pmem.coe

path=$(echo $(pwd)/pmem.coe)

cd ../../../rtl/verilog/coregen
ls | grep -Ev ".cgp|.xco" | xargs rm -rf

sed -ie "s/write_depth_a=.*/write_depth_a=$pmemsize/g" spartan6_pmem.xco
sed -ie "s/write_depth_a=.*/write_depth_a=$dmemsize/g" spartan6_dmem.xco

sed -i "s\CSET coe_file=.*\$\CSET coe_file=$path\g" *.xco

coregen -b spartan6_pmem.xco -p coregen.cgp
coregen -b spartan6_dmem.xco -p coregen.cgp
# coregen -b clock.xco -p coregen.cgp

ls *.xcoe | xargs rm -rf
