#!/bin/bash

set -e # exit

source ../bin/helper.sh
load_c_defines

echo "memory_initialization_radix=16;" > pmem.coe
echo "memory_initialization_vector=10;" >> pmem.coe

path=$(echo $(pwd)/pmem.coe)

cd ../../../rtl/verilog/coregen
ls | grep -Ev ".cgp|.xco" | xargs rm -rf

sed -ie "s/write_depth_a=.*/write_depth_a=$pmemsize/g" spartan6_pmem.xco
sed -ie "s/write_depth_a=.*/write_depth_a=$dmemsize/g" spartan6_dmem.xco

sed -i "s\CSET coe_file=.*\$\CSET coe_file=$path\g" *.xco

coregen -b spartan6_pmem.xco -p coregen.cgp
coregen -b spartan6_dmem.xco -p coregen.cgp
coregen -b clock.xco -p coregen.cgp

ls *.xcoe | xargs rm -rf
