#!/bin/bash

INIT_TEST="================= START SIMULATION =============="
END_TEST="================== END SIMULATION ==============="

function red () {
    printf "\e[31m$1\e[0m"
}

function green () {
    printf "\e[32m$1\e[0m"
}

# This file will run tests in tests describe in tests
for file in ./tests/*
do
    (
        printf "%-40sRunning" "$file:"
        hash=$(md5sum "$file" | cut -d" " -f1 -)

        sed -e "/$INIT_TEST/,\$d" $file > /tmp/smart_bash_$hash
        sed -n -e "/$INIT_TEST/,\$p" $file > /tmp/smart_exp_result_$hash

        bash /tmp/smart_bash_$hash > /tmp/smart_result_$hash 2> /dev/null

        printf "\b\b\b\b\b\b\b"
        printf "        "
        printf "\b\b\b\b\b\b\b"

        sed -n -e "/$INIT_TEST/,\$p" /tmp/smart_result_$hash > /tmp/r_$hash
        sed -e "/$END_TEST/,\$d" /tmp/r_$hash > /tmp/smart_result_$hash

        result=$(diff /tmp/smart_result_$hash /tmp/smart_exp_result_$hash)

        if [ $? -eq 0 ]
        then
            green "OK\n"
        else
            red "ERROR\n\n"
            diff /tmp/smart_result_$hash /tmp/smart_exp_result_$hash
        fi
    ) 
done

wait
